ploomber/doc

examples/quickstart/notebook.ipynb

This fixes the issue with the sample data, all of the combinations should pass now without exceptions.
We should think if we want to just host our own xls so this doesn't take 10-20 seconds extra for the user to compose the dataset on start (vs having it ready and just download it from github).
Closes https://github.com/ploomber/cloud-backend/issues/259
@edublancas I wasn't sure how I can get rid of the success outputs, I tried minimizing the feedback: `SqlMagic.feedback=0` but it didn't work. Any ideas?

Adding sample data to penguins

---

doc/_toc.yml
doc/apps/chalk-it.md
examples/docker/chalk-it/Dockerfile

Deployement of a Chalk'it projet into Plommber cloud documented.
----
:books: Documentation preview :books:: https://ploomber-doc--49.org.readthedocs.build/en/49/

documenting usage of Ploomber Cloud for Chalk'it dashboards deployement

---

doc/user-guide/cli.md

- Edit `cli.md` to include instructions for `init --from-existing` under 'Configure an existing project'
----
:books: Documentation preview :books:: https://ploomber-doc--53.org.readthedocs.build/en/53/

Init From Existing Instructions

---

doc/apps/solara.md

Now that Ploomber supports solara, users don't need to upload a docker file.
Updates to doc
----
📚 Documentation preview 📚: https://ploomber-doc--78.org.readthedocs.build/en/78/

fix documentation for solara

---

doc/user-guide/cli.md
doc/user-guide/env-vars.md

- Added `Defining environment variables` section in `cli.md` to document support for secrets. Instructs users on how to configure secrets using `.env` file and deploy the project. Also links to `env_vars.md` for instructions on how to access and verify secrets from their application
- Added a note in `env_vars.md` that directs users to `cli.md` if they want to configure environment variables there
Related PR: https://github.com/ploomber/cli/pull/33
----
📚 Documentation preview 📚: https://ploomber-doc--98.org.readthedocs.build/en/98/

Add instructions for secrets in CLI

---

doc/apps/streamlit.md

This PR fixes a minor typo in the guide about deploying Streamlit apps on Ploomber Cloud. The current guide names Panel but links to Streamlit's docs.
----
📚 Documentation preview 📚: https://ploomber-doc--99.org.readthedocs.build/en/99/

Typo: replace Panel with Streamlit in Streamlit deployment guide

---

examples/panel/rag-news/README.md
examples/panel/rag-news/rag_news.py

1. Fixes error `FileNotFoundError: [Errno 2] No such file or directory: 'embeddings.json'` when downloading embeddings  for the first time.
2. Added more details to README.md.
Closes #123 
----
📚 Documentation preview 📚: https://ploomber-doc--125.org.readthedocs.build/en/125/

Rag news example fixes

---

doc/apps/panel.md
doc/apps/solara.md
doc/apps/streamlit.md

Added Testing Locally sections

---

doc/apps/dash.md
doc/user-guide/cli.md

- Now that Dash is supported natively, updated the deployment instructions to be similar to the other supported frameworks. Includes instructions on deploying an example from the CLI
- Also noticed that this note on the CLI page is not updated: 
Updated it since we now support Voila and environment variables.
----
📚 Documentation preview 📚: https://ploomber-doc--141.org.readthedocs.build/en/141/

Update Dash documentation

---

doc/_toc.yml
doc/apps/hyperdiv.md
examples/docker/hyperdiv/Dockerfile
examples/docker/hyperdiv/app.py

This PR adds:
* A Hyperdiv example app in `examples/docker/hyperdiv`
* A Hyperdiv deployment doc page in `doc/apps/hyperdiv.md`
----
📚 Documentation preview 📚: https://ploomber-doc--149.org.readthedocs.build/en/149/

Hyperdiv docs

---

doc/features/serverless-fns.md

----
📚 Documentation preview 📚: https://ploomber-doc--173.org.readthedocs.build/en/173/

Serverless function

---

examples/chainlit/private-chatgpt/Dockerfile
examples/chainlit/private-chatgpt/README.md
examples/chainlit/private-chatgpt/app.py
examples/chainlit/private-chatgpt/chainlit.md
examples/chainlit/private-chatgpt/requirements.txt

- Added `examples/chainlit/private-chatgpt` which is the Chainlit UI for this blog post:
https://github.com/ploomber/ploomber.io/pull/154
----
📚 Documentation preview 📚: https://ploomber-doc--176.org.readthedocs.build/en/176/

Private ChatGPT Chainlit Example

---

doc/_config.yml
doc/features/serverless-fns.md
doc/user-guide/cli.md
doc/user-guide/github.md
doc/user-guide/gpu.md
doc/user-guide/secrets.md

Closes #185 #193 
----
📚 Documentation preview 📚: https://ploomber-doc--195.org.readthedocs.build/en/195/

Added missing options in CLI guide

---

doc/user-guide/cli.md
doc/user-guide/gpu.md
doc/user-guide/resources.md

- Added documentation for `ploomber-cloud resources` under `cli.md`, `resources.md`, and `gpu.md`
See this PR: https://github.com/ploomber/cli/pull/83
----
📚 Documentation preview 📚: https://ploomber-doc--203.org.readthedocs.build/en/203/

Document `ploomber-cloud resources`

---

doc/user-guide/cli.md
doc/user-guide/github.md

----
📚 Documentation preview 📚: https://ploomber-doc--211.org.readthedocs.build/en/211/

Watch incremental

---

doc/user-guide/cli.md
doc/user-guide/github.md

Documentation for https://github.com/ploomber/cli/pull/100
- Described workflow in `user-guide/github.md`
- Linked to this description in `secrets` section of `cli.md`
----
📚 Documentation preview 📚: https://ploomber-doc--212.org.readthedocs.build/en/212/

Document secrets via config and environment variables workflow

---

doc/user-guide/cli.md

docs for this: https://github.com/ploomber/cli/pull/101
----
📚 Documentation preview 📚: https://ploomber-doc--215.org.readthedocs.build/en/215/

adds `--config/-c` doc

---

doc/apps/chainlit.md
doc/apps/dash.md
examples/chainlit/app-with-auth0/Dockerfile
examples/chainlit/app-with-auth0/app.py
examples/chainlit/app-with-auth0/chainlit.md
examples/dash/app-with-auth0/app.py
examples/dash/app-with-auth0/requirements.txt

----
📚 Documentation preview 📚: https://ploomber-doc--222.org.readthedocs.build/en/222/

Dash, Chainlit auth0 example

---

doc/user-guide/cli.md

Closes #239 
----
📚 Documentation preview 📚: https://ploomber-doc--245.org.readthedocs.build/en/245/

Document `logs`

---

doc/user-guide/cli.md

- Mentions auth0 in addition to vllm as supported templates
Closes https://github.com/ploomber/cli/issues/129
----
📚 Documentation preview 📚: https://ploomber-doc--255.org.readthedocs.build/en/255/

Add Auth0 to CLI templates section

---

doc/user-guide/cli.md

- Added documentation supporting user custom ignore in ploomber-cloud.json
Closes [ploomber/cli#45](https://github.com/ploomber/cli/issues/45)
----
📚 Documentation preview 📚: https://ploomber-doc--256.org.readthedocs.build/en/256/

Doc for ignore section in ploomber-cloud.json

---

doc/user-guide/cli.md
doc/user-guide/managing-apps.md
examples/panel/stock-market-chatbot/README.md

documentation for https://github.com/ploomber/cli/issues/94
----
📚 Documentation preview 📚: https://ploomber-doc--261.org.readthedocs.build/en/261/

Add documentation for `ploomber-cloud labels --sync`

---

doc/apps/docker.md
doc/user-guide/dockerfile.md

----
📚 Documentation preview 📚: https://ploomber-doc--281.org.readthedocs.build/en/281/

feat(docker): now available on all tier

---

doc/user-guide/password.md

----
📚 Documentation preview 📚: https://ploomber-doc--283.org.readthedocs.build/en/283/

[Feature] Documentation for nginx authentication with the CLI

---

examples/panel/weights-and-biases-llm/requirements.txt
examples/streamlit/mirascope-url-extractor/app.py
examples/streamlit/mirascope-url-extractor/requirements.txt
examples/voila/mosaic/requirements.txt

While testing some example apps to test https://github.com/ploomber/cloud-frontend/pull/601, the following three were having runtime errors due to the fact that the newer versions of the dependencies used are not backward compatible.
----
📚 Documentation preview 📚: https://ploomber-doc--285.org.readthedocs.build/en/285/

[Bug] Outdated dependencies in example

---

doc/user-guide/cli.md

Updated documentation for the change introduce in: https://github.com/ploomber/cli/pull/146
---
Related to https://github.com/ploomber/cli/issues/143
----
📚 Documentation preview 📚: https://ploomber-doc--286.org.readthedocs.build/en/286/

[Feature] Documentation for downloading project w/ `CLI`

---

doc/user-guide/cli.md

Close: https://github.com/ploomber/cli/pull/146#discussion_r1787222055
----
📚 Documentation preview 📚: https://ploomber-doc--287.org.readthedocs.build/en/287/

[Feature] Documentation on the `--config` flag when using init

---

doc/faq/faq.md
doc/pricing/overview.md

While reading the doc, I saw that there were still some artefact that docker is Pro only
----
📚 Documentation preview 📚: https://ploomber-doc--288.org.readthedocs.build/en/288/

[Bug] Docker is available on all tier

---

doc/apps/dash.md

----
📚 Documentation preview 📚: https://ploomber-doc--293.org.readthedocs.build/en/293/

[Doc] Dash - auto change in routing | note

---

examples/streamlit/app-with-auth0/app.py
examples/streamlit/app-with-auth0/readme.md

- Updated the depreciated code
- I also added a `readme.md`, because if someone look at it without coming from the docs, this one will have no idea on how to get started
closes #299 
----
📚 Documentation preview 📚: https://ploomber-doc--300.org.readthedocs.build/en/300/

[Bug] Deprecated stremalit api for Auth0 example

---

doc/apps/dash.md
doc/apps/flask.md
doc/apps/jupyterlab.md
doc/apps/mlflow.md
doc/apps/panel.md
doc/apps/vllm.md
doc/intro.md
doc/user-guide/cli.md
doc/user-guide/custom-domains.md
doc/user-guide/password.md

- **BUG FIX** Remove the link in the demo to application that doesn't exist anymore
- **DOC** Mention that we are slowly migrating to `ploomber.app` where `ploomberapp.io` is mentionned
closes: https://github.com/ploomber/doc/issues/301
----
📚 Documentation preview 📚: https://ploomber-doc--303.org.readthedocs.build/en/303/

[Doc] Mention multiple domain possible `ploomber.app` & `ploomberapp.io`

---

.readthedocs.yml
doc/faq/faq.md

closes https://github.com/ploomber/doc/issues/308
----
📚 Documentation preview 📚: https://ploomber-doc--309.org.readthedocs.build/en/309/

[Doc] How to Include Private Packages

---

doc/user-guide/custom-domains.md

Same as: https://github.com/ploomber/cloud-frontend/pull/753

[Doc] SquareSpace SSL change needed

---

doc/user-guide/cli.md

----
📚 Documentation preview 📚: https://ploomber-doc--311.org.readthedocs.build/en/311/

[Doc] CLI dev mode docs added

---

misc/ai-spam-email-monitor/README.md
misc/ai-spam-email-monitor/README_gemini.md
misc/ai-spam-email-monitor/auth.py
misc/ai-spam-email-monitor/gemini_spam_detector.py
misc/ai-spam-email-monitor/gmail_monitor.py
misc/ai-spam-email-monitor/requirements.txt

----
📚 Documentation preview 📚: https://ploomber-doc--317.org.readthedocs.build/en/317/

AI Spam Email Monitor
